version: 2

sources:
  - name: raw
    description: "Raw data loaded from Yahoo Finance"
    database: MLDS430
    schema: COBRA
    tables:
      - name: stock_prices_daily
        description: "Daily OHLCV stock prices"
        columns:
          - name: symbol
            description: "Stock ticker symbol"
          - name: date
            description: "Trading date"
          - name: close
            description: "Closing price"
            tests:
              - not_null

      - name: company_info
        description: "Company fundamentals and profile"
        columns:
          - name: symbol
            description: "Stock ticker symbol"
            tests:
              - not_null

      - name: benchmark_series_daily
        description: "Benchmark indices and macro indicators"
        columns:
          - name: series_ticker
            description: "Benchmark ticker (e.g., ^GSPC)"
          - name: date
            description: "Date"
          - name: value
            description: "Index value"

models:
  - name: stg_stock_prices
    description: "Cleaned and deduplicated stock prices with calculated metrics"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: close
        description: "Closing price"
        tests:
          - not_null
      - name: daily_return
        description: "Daily return as decimal (close-to-close)"

  - name: stg_company_info
    description: "Latest company information per symbol"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - unique
          - not_null
      - name: company_name
        description: "Company name"

  - name: stg_benchmark_series
    description: "Cleaned benchmark series with changes"
    columns:
      - name: series_ticker
        description: "Benchmark ticker"
        tests:
          - not_null
      - name: date
        description: "Date"
        tests:
          - not_null
      - name: value
        description: "Benchmark value"
        tests:
          - not_null
